a=input("Enter first number: ")
b=input("Enter second number: ")
print("Addition of",a,"and",b,"is",int(a)+int(b))
print("Subtraction of",a,"and",b,"is",int(a)-int(b))
print("Multiplication of",a,"and",b,"is",int(a)*int(b))
print("Divison of",a,"and",b,"is",int(a)/int(b))
